src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Models/Conocimiento/ConocimientoIndexModel.cs
using EscuelaNet.Dominio.Conocimientos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EscuelaNet.Presentacion.Conocimientos.Web.Models
{
    public class ConocimientoIndexModel
    {
        public string Titulo { get; set; }
        public int IdCategoria { get; set; }
        public string Nombre { get; set; }
        public IList<Conocimiento> Conocimientos { get; set; }
        
    }
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Models/Conocimiento/NuevaConocimientoModel.cs
using EscuelaNet.Dominio.Conocimientos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EscuelaNet.Presentacion.Conocimientos.Web.Models
{
    public class NuevaConocimientoModel
    {
        public string Titulo { get; set; }
        public int IdCate { get; set; }
        public int IdConocimiento { get; set; }
        public string Nombre { get; set; }
        public Demanda Demanda { get; set; }
    }
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Controllers/ConocimientoController.cs
using EscuelaNet.Presentacion.Conocimientos.Web.Infraestructura;
using EscuelaNet.Presentacion.Conocimientos.Web.Models;
using EscuelaNet.Dominio.Conocimientos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Conocimientos.Web.Controllers
{
    public class ConocimientoController : Controller
    { 
        public ActionResult Index(int id)
        {
            var categoria = Contexto.Instancia.Categorias[id];
            var model = new ConocimientoIndexModel()
            {
                Nombre = string.Format("Categoria {1} - Conocimiento de {0}", categoria.Nombre, categoria.Descripcion),
                Conocimientos = (List<Conocimiento>)categoria.Conocimientos,
                IdCategoria = id

            };
        return View(model);
        }

        //public ActionResult Index(int id) {
        //    var equipo = Contexto.Instancia.Equipos[id];
        //    var model = new ProgramadoresIndexModel()
        //    {
        //        Titulo = string.Format("Equipo {1} - Programadores de {0}", equipo.Pais, equipo.Nombre),
        //        Programadores = (List<Programador>)equipo.Programadores,
        //        idEquipo = id }; return View(model);
        //}


        public ActionResult New(int id)
    {
            var categoria = Contexto.Instancia.Categorias[id];
            var model = new NuevaConocimientoModel()
            {
                Titulo = "Nuevo Conocimiento para la Categoria '"+categoria.Nombre+"'", 
                IdCate = id

            };
            return View(model);
    }

    [HttpPost]
    public ActionResult New(NuevaConocimientoModel model)
    {
        if (!string.IsNullOrEmpty(model.Nombre))
        {
                try
                {
                    var idCono = model.IdConocimiento;
                    Contexto.Instancia.Categorias[model.IdCate].AgregarConocimiento(new Conocimiento(model.Nombre));

                    TempData["success"] = "Nuevo conocimiento Creado";
                    return RedirectToAction("Index/"+model.IdCate);
                }
                catch (Exception ex)
                {
                TempData["error"] = ex.Message;
                return View(model);
                }
        }
        else
        {
            TempData["error"] = "Texto vacío";
            return View(model);

        }
    }


    public ActionResult Edit(int idCategoria, int idConocimiento)
        {
            var cantCategoria = Contexto.Instancia.Categorias.Count();

            if (idCategoria < 0 || idCategoria >= cantCategoria || idConocimiento <0)
            {
                TempData["error"] = "Id no valido";
                return RedirectToAction("Index");
            }
            else
            {
                var categoria = Contexto.Instancia.Categorias[idCategoria];
                var conocimiento = categoria.Conocimientos[idConocimiento];

                var model = new NuevaConocimientoModel()
                {
                    IdCate = idCategoria,
                    IdConocimiento = idConocimiento,
                    Nombre = conocimiento.Nombre,
                    Demanda = conocimiento.Demanda,
                                       
                };

                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Edit(NuevaConocimientoModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    Contexto.Instancia.Categorias[model.IdCate].Conocimientos[model.IdConocimiento].Nombre = model.Nombre;
                    Contexto.Instancia.Categorias[model.IdCate].Conocimientos[model.IdConocimiento].Demanda = model.Demanda;
                    TempData["success"] = "Conocimiento editado";
                    return RedirectToAction("Index/"+model.IdCate);
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }

            }
            else
            {
                TempData["error"] = "Texto vacío";
                return View(model);
            }
        }


        public ActionResult Delete(int idCategoria, int idConocimiento)
        {
            var cantidad = Contexto.Instancia.Categorias.Count();
            if (idCategoria < 0 || idCategoria >= cantidad || idConocimiento < 0)
            {
                TempData["error"] = "Id no válido";
                return RedirectToAction("Index");
            }
            else
            {
                var categoria = Contexto.Instancia.Categorias[idCategoria];
                var conocimiento = categoria.Conocimientos[idConocimiento];

                var model = new NuevaConocimientoModel()
                {
                    Titulo = "Algo",
                    IdCate = idCategoria,
                    IdConocimiento = idConocimiento,
                    Nombre = conocimiento.Nombre,
                    Demanda = conocimiento.Demanda
                };
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Delete(NuevaConocimientoModel model)
        {

            try
            {
                Contexto.Instancia.Categorias[model.IdCate].Conocimientos.RemoveAt(model.IdConocimiento);
                TempData["success"] = "Conocimiento Borrado";
                return RedirectToAction("../Conocimiento/Index/" + model.IdCate);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }

        }


        //public ActionResult Delete(int id)
        //{
        //    var categoria = Contexto.Instancia.Conocimientos[id];
        //    var model = new NuevaConocimientoModel()
        //    {
        //        Nombre = categoria.Nombre,
        //        Id = id
        //    };
        //    return View(model);

        //}
        //[HttpPost]
        //public ActionResult Delete(NuevaConocimientoModel model)
        //{
        //    try
        //    {
        //        Contexto.Instancia.Conocimientos.RemoveAt(model.Id);
        //        TempData["success"] = "Conocimiento borrado";
        //        return RedirectToAction("Index");
        //    }
        //    catch (Exception ex)
        //    {
        //        TempData["error"] = ex.Message;
        //        return View(model);
        //    }
        //}
    }
    


    }

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/Delete.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.NuevaConocimientoModel

@{
    ViewBag.Title = "Borrar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Borrar categoria</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IdCate)
                    @Html.HiddenFor(model => model.IdConocimiento)
                    <div class="box-body">
                        <p>
                            ¿Está seguro de borrar la linea "@Model.Nombre"?
                        </p>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <a href="/Conocimiento/Index/@Model.IdCate"> Cancelar</a>
                        @*<button id="cancel" name="cancel" class="btn btn-default" value="1">Cancelar</button>*@

                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    @Html.ActionLink("Volver al Incio", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/Edit.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.NuevaConocimientoModel

@{
    ViewBag.Title = "Editar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo Conocimiento</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IdCate)
                    @Html.HiddenFor(model => model.IdConocimiento)


                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Demanda, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EnumDropDownListFor(m => m.Demanda, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Demanda, "", new { @class = "help-block with errors" })
                        </div>
                    </div>


                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                        <button type="submit" class="btn btn-primary">Cancelar</button>
                    </div>


                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/Index.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.ConocimientoIndexModel


@{
    ViewBag.Title = "Index";
    //var x = 1;
    //for (var i = 10; i > 0; i--)
    //{
    //    x *= i;
    //}
}

<div class="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Nuevos Conocimientos</h3>
                <label class="text-success">@TempData["success"]</label>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Nombre</th>
                            <th>Demanda</th>
                            <th>Acciones</th>
                        </tr>
                        @foreach (var conocimiento in Model.Conocimientos)
                        {
                            <tr>
                                <td>@Model.Conocimientos.IndexOf(conocimiento)</td>
                                <td>@conocimiento.Nombre</td>
                                <td>@conocimiento.Demanda</td>
                                @*@foreach(var asesor in conocimiento.Asesores)
                                {
                                    <td>@asesor.Nombre</td>
                                }*@
                                <td>
                                    <a href="/Conocimiento/edit/?IdCategoria=@Model.IdCategoria&IdConocimiento=@Model.Conocimientos.IndexOf(conocimiento)" title="Editar" class="btn btn-toolbar">
                                        <label class="label bg-gray"><i class="fa fa-edit"></i>Editar</label>
                                    </a>
                                    <a href="/Conocimiento/delete/?IdCategoria=@Model.IdCategoria&IdConocimiento=@Model.Conocimientos.IndexOf(conocimiento)" title="borrar" class="btn btn-toolbar">
                                        <label class="label bg-gray"><i class="fa fa-remove"></i>Borrar</label>
                                    </a>
                                </td>
                                <td>
                                    <a href="../../Asesor/new/?IdCategoria=@Model.IdCategoria&IdConocimiento=@Model.Conocimientos.IndexOf(conocimiento)" title="Crear Asesor" class="btn btn-toolbar">
                                    <label class="label bg-gray"><i class="fa fa-plus"></i>Crear Asesor</label>
                                    </a>
                                    <a href="../../Asesor/index/?IdCategoria=@Model.IdCategoria&IdConocimiento=@Model.Conocimientos.IndexOf(conocimiento)" title="Crear Asesor" class="btn btn-toolbar">
                                        <label class="label bg-gray"><i class="fa fa-plus"></i>Asesor</label>
                                    </a>
                                </td>
                            </tr>
                        }
                        <tr>
                            <td></td>
                            <td></td>
                            <td>
                                <a href="/Conocimiento/new/@Model.IdCategoria" title="Nuevo" class="btn btn-toolbar">
                                    <label class="label bg-gray"><i class="fa fa-plus"></i>Nuevo</label>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
                <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">«</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">»</a></li>
                </ul>
            </div>
        </div>
        <!-- /.box -->
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <!-- /.col -->
</div>

@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Conocimientos.Web/Views/Conocimiento/New.cshtml
@model EscuelaNet.Presentacion.Conocimientos.Web.Models.NuevaConocimientoModel

@{
    ViewBag.Title = "New";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Nueva linea de produccion</h3>
                <label class="text-danger">@TempData["error"]</label>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Html.BeginForm("New", "Conocimiento", null,
                       FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myForm" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="box-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar el nombre del proyecto.", data_minlength = "5" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "help-block with-errors" })
                    </div>
                    
                    <div class="form-group">
                        @Html.LabelFor(model => model.Demanda, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EnumDropDownListFor(m => m.Demanda, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Demanda, "", new { @class = "help-block with errors" })
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Crear</button>
                    <a href="/Conocimiento/Index"> Cancelar</a>
                </div>
                
            }

        </div>
        <!-- /.box -->
    </div>

</div>
<div>
    @Html.ActionLink("Volver al Inicio", "Index")
</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
        $(document).ready(function () {
            $('#myForm').validator()
        });
    </script>
}