src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Controllers/EtapasController.cs
using EscuelaNet.Presentacion.Proyectos.Web.Infraestructura;
using EscuelaNet.Presentacion.Proyectos.Web.Models;
using EscuelaNet.Dominio.Proyectos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EscuelaNet.Presentacion.Proyectos.Web.Controllers
{
    public class EtapasController : Controller
    {
        // GET: Etapa
        public ActionResult Index(int idLinea, int idProy)
        {

            var etapas = Contexto.Instancia.LineasDeProduccion[0].Proyectos[0];
            var model = new EtapaIndexModel();
            model.Nombre = string.Format("Etapa {0}", etapas.Nombre);
            model.Etapas = (List<Etapa>)etapas.Etapas;
            model.IDLinea = idLinea;
            model.IDProy = idProy;

            return View(model);

        }

        public ActionResult New()
        {
            var model = new NuevaEtapaModel();
            return View(model);
        }

        [HttpPost]

        public ActionResult New(NuevaEtapaModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    Contexto.Instancia.LineasDeProduccion[model.IDLinea].Proyectos[model.IDProy].PushEtapa(model.Nombre, model.duracion);
                    TempData["success"] = "La etapa se ha creado";
                    return RedirectToAction("Index", new { idLinea = model.IDLinea, idProy = model.IDProy });
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
            } else
            {
                TempData["error"] = "Debe completar ambos campos ";
                return View(model);
            }
        }

        public ActionResult Edit(int idProy, int idLinea, int idEtapa)
        {
            var etapas = Contexto.Instancia.LineasDeProduccion[idLinea].Proyectos[idProy].Etapas[idEtapa];
            var model = new NuevaEtapaModel()
            {
                Nombre = etapas.Nombre,
                ID = idEtapa,
                duracion = etapas.Duracion,
                IDLinea = idLinea,
                IDProy = idProy
            };
            return View(model);
        }

        [HttpPost]

        public ActionResult Edit(NuevaEtapaModel model)
        {
            if (!string.IsNullOrEmpty(model.Nombre))
            {
                try
                {
                    Contexto.Instancia.LineasDeProduccion[model.IDLinea].Proyectos[model.IDProy].Etapas[model.ID].Nombre = model.Nombre;
                    Contexto.Instancia.LineasDeProduccion[model.IDLinea].Proyectos[model.IDProy].Etapas[model.ID].Duracion = model.duracion;

                    TempData["success"] = "Etapa modificada";
                    return RedirectToAction("index", new { idLinea=model.IDLinea,idProy=model.IDProy }); 
                }
                catch(Exception ex)
                {
                    TempData["error"] = ex.Message;
                    return View(model);
                }
            }
            else
            {
                TempData["error"] = "Debe completar ambos campos";
                return View(model);
            }
        }

        public ActionResult Delete(int idLinea, int idProy, int idEtapa)
        {
            var etapas = Contexto.Instancia.LineasDeProduccion[idLinea].Proyectos[idProy].Etapas[idEtapa];
            var model = new NuevaEtapaModel()
            {
                Nombre = etapas.Nombre,
                ID = idEtapa
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(NuevaEtapaModel model)
        {
            try
            {
                Contexto.Instancia.LineasDeProduccion[model.IDLinea].Proyectos[model.IDProy].Etapas.RemoveAt(model.ID);
                TempData["success"] = "Etapa eliminada";
                return RedirectToAction("Index", new { idLinea=model.IDLinea, idProy = model.IDProy });
            }
            catch(Exception ex)
            {
                TempData["error"] = ex.Message;
                return View(model);
            }
        }



    }
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/Delete.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaModel

@{
    ViewBag.Title = "Borrar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Borrar proyecto</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm())
                {   
                    
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    <div class="box-body">
                        <p>
                            ¿Está seguro de borrar la etapa <strong>"@Model.Nombre"</strong> ?
                        </p>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Aceptar</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    <a href="/Etapas/Index/?idLinea=@Model.IDLinea&idProy=@Model.IDProy">Volver a lista de Etapas</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/Edit.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaModel

@{
    ViewBag.Title = "Editar";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo proyectos</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
           
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.IDLinea)
                    @Html.HiddenFor(model => model.IDProy)
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Este campo es obligatorio.", data_minlength = "1" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.duracion, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.duracion, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Este campo es obligatorio.", data_minlength = "1" } })
                            @Html.ValidationMessageFor(model => model.duracion, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Editar</button>
                    </div>
                    <div class="box-footer">
                        <a href="/Home/Index">Cancelar</a>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>

}
<div>
    <a href="/Etapas/Index/?idLinea=@Model.IDLinea&idProy=@Model.IDProy">Volver a lista de Etapas</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/Index.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.EtapaIndexModel

@{
    ViewBag.Title = "Index";
    var x = 1;
    for (var i = 10; i > 0; i--)
    {
        x *= i;
    }
}

<div class="row">
        <div class="col-md-6">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Etapas</h3>
                <label class="text-success">@TempData["success"]</label>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">
                  <tbody>
                      <tr>
                          <th style="width: 10px">#</th>
                          <th>Título</th>
                          <th>Acciones</th>
                      </tr>
                      @Model.IDProy
                      @foreach (var etapa in Model.Etapas)
                      {
                          <tr>
                              <td>@Model.Etapas.IndexOf(etapa)</td>
                              <td>@etapa.Nombre</td>
                              <td>
                                  <a href="/Etapas/edit/?idLinea=@Model.IDLinea&idProy=@Model.IDProy&idEtapa=@Model.Etapas.IndexOf(etapa)" title="Editar" class="btn btn-toolbar">
                                      <label class="label bg-gray"><i class="fa fa-edit"></i> Editar</label>
                                  </a>
                                  <a href="/Etapas/delete/?idLinea=@Model.IDLinea&idProy=@Model.IDProy&idEtapa=@Model.Etapas.IndexOf(etapa)" title="borrar" class="btn btn-toolbar">
                                      <label class="label bg-gray"><i class="fa fa-remove"></i> Borrar</label>
                                  </a>
                              </td>
                          </tr>

                      }
                      <tr>
                          <td></td>
                          <td></td>
                          <td>
                              <a href="/Etapas/New" title="Nuevo" class="btn btn-toolbar">
                                  <label class="label bg-gray"><i class="fa fa-plus"></i> Nuevo</label>
                              </a>
                          </td>
                      </tr>
                  </tbody></table>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              <ul class="pagination pagination-sm no-margin pull-right">
                <li><a href="#">«</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">»</a></li>
              </ul>
            </div>
          </div>
          <!-- /.box -->

          <!-- /.box -->
        </div>
        <!-- /.col -->
        <!-- /.col -->
      </div>
      <a href="/Proyectos/Index/@Model.IDLinea">Volver a lista de Proyectos</a>
@section Scripts{
    <script>
    </script>
}

src/Presentacion/EscuelaNet.Presentacion.Proyectos.Web/Views/Etapas/New.cshtml
@model EscuelaNet.Presentacion.Proyectos.Web.Models.NuevaEtapaModel

@{
    ViewBag.Title = "New";
}




    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo proyecto</h3>
                    <label class="text-danger">@TempData["error"]</label>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @using (Html.BeginForm("New", "Etapas", null,
           FormMethod.Post, new { role = "form", data_toggle = "validator", @id = "myForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IDLinea)
                    @Html.HiddenFor(model => model.IDProy)
                    

                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar el nombre la Etapa.", data_minlength = "5" } })
                            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.duracion, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.duracion, new { htmlAttributes = new { @class = "form-control", required = "required", data_error = "Debe ingresar la duración de la Etapa", data_minlength = "1" } })
                            @Html.ValidationMessageFor(model => model.duracion, "", new { @class = "help-block with-errors" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                }

            </div>
            <!-- /.box -->
        </div>

    </div>
<div>
    <a href="/Etapas/Index/?idLinea=@Model.IDLinea&idProy=@Model.IDProy">Volver a lista de Etapas</a>
</div>

@section Scripts {
    <script src="~/lib/1000hz-bootstrap-validator/validator.js"></script>
    <script>
        $(document).ready(function () {
            $('#myForm').validator()
        });
    </script>
}